[[bin]]
name = "fuzzer"
path = "Source/main.rs"

[dependencies]
oxc = { version = "0.48.0", features = ["full"]}

libfuzzer-sys = "0.4.8"
oxc = { version = "0.48.0", features = ["full"]}

[package]
edition = "2024"
name = "fuzzer"
publish = false
version = "0.0.1"
