name: CI

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**/*.rs'
      - 'Cargo.lock'
      - 'rust-toolchain.toml'
  push:
    branches:
      - main
    paths:
      - '**/*.rs'
      - 'Cargo.lock'
      - 'rust-toolchain.toml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@v1

      - uses: oxc-project/setup-rust@v1.0.0
        with:
          save-cache: ${{ github.ref_name == 'main' }}

      - run: cargo check
