name: Cargo Fuzz

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  fuzz:
    name: Cargo Fuzz
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@v1

      - uses: oxc-project/setup-rust@v1.0.0

      - run: cargo install cargo-fuzz

      - name: Run Fuzzer
        run: cargo +nightly fuzz run --sanitizer none --release parser -- -only_ascii=1 -detect_leaks=0 -max_total_time=900
